Fix some GCC 5.3 Errors: 	(gcc version 5.3.1 20160303 (optimized) (UBERTC-5.3.x))
 - kernel: add support for gcc 5

	add:	include/linux/compiler-gcc5.h

	Signed-off-by: boredSleepyHungryJoblessGuy <randomlyjobless@openmailbox.org>
	Signed-off-by: Akhil Narang <something@akhilnarang.xyz>

 - ARM: 8160/1: drop warning about return_address not using unwind tables

	The warning was introduced in 2009 (commit 4bf1fa5 ([ARM] 5613/1:
	implement CALLER_ADDRESSx)). The only "problem" here is that
	CALLER_ADDRESSx for x > 1 returns NULL which doesn't do much harm.

	The drawback of implementing a fix (i.e. use unwind tables to implement
	CALLER_ADDRESSx) is that much of the unwinder code would need to be
	marked as not traceable.

	changed files:	arch/arm/kernel/return_address.c

	Signed-off-by: Uwe Kleine-König <u.kleine-koenig@pengutronix.de>
	Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>
	Signed-off-by: Akhil Narang <something@akhilnarang.xyz>

 - arm: LLVMLinux: use static inline in ARM ftrace.h

	With compilers which follow the C99 standard (like modern versions of gcc and
	clang), "extern inline" does the wrong thing (emits code for an externally
	linkable version of the inline function). In this case using static inline
	and removing the NULL version of return_address in return_address.c does
	the right thing.

	changed files:	arch/arm/include/asm/ftrace.h
					arch/arm/kernel/return_address.c

	Signed-off-by: Behan Webster <behanw@converseincode.com>
	Reviewed-by: Mark Charlebois <charlebm@gmail.com>

 - mach-msm: Fix qdsp6v2 compile with 5.0

	changed files:	 arch/arm/mach-msm/include/mach/qdsp6v2/apr.h

	Signed-off-by: Chet Kener <Cl3Kener@gmail.com>
	Signed-off-by: Akhil Narang <something@akhilnarang.xyz>

 - mm: Fix rmap compile for GCC 5.0

	changed files:	 mm/rmap.c

	Signed-off-by: Chet Kener <Cl3Kener@gmail.com>
	Signed-off-by: Akhil Narang <something@akhilnarang.xyz>

 - gpu:msm: Fix ringbuffer 5.0 compile

	changed files:	 drivers/gpu/msm/adreno_ringbuffer.c

Signed-off-by: Chet Kener <Cl3Kener@gmail.com>
Signed-off-by: Akhil Narang <something@akhilnarang.xyz>

 - gpu:msm: Fix 5.0 compile

	* These need to be static to avoid these errors:

	drivers/built-in.o: In function `.LANCHOR1':
	msm_iommu_sec.c:(.data+0x9298): undefined reference to `kgsl_iommu_sync_lock'
	msm_iommu_sec.c:(.data+0x929c): undefined reference to `kgsl_iommu_sync_unlock'
	Makefile:877: recipe for target '.tmp_vmlinux1' failed
	make: *** [.tmp_vmlinux1] Error 1

	changed files:	 drivers/gpu/msm/kgsl_iommu.c

Signed-off-by: Chet Kener <Cl3Kener@gmail.com>

 - Fix More GCC 5.0 Errors

	changed files:	 drivers/media/platform/msm/camera_v2/jpeg_10/msm_jpeg_sync.c
					 drivers/media/platform/msm/vcap/vcap_vc.c
					 lib/decompress_unlzo.c

Signed-off-by: Chet Kener <Cl3Kener@gmail.com>
Signed-off-by: Akhil Narang <something@akhilnarang.xyz>

 - gcc5: drivers/video/msm/mdss/mdss_mdp_pp.c: warning: comparison of constant '15'...
	...with boolean expression is always false

	changed files:	 drivers/video/msm/mdss/mdss_mdp_pp.c

	Signed-off-by: ooOJust4FunOoo

 - gcc5: sound/soc/codecs/wcd9xxx-mbhc.c fix warning: initialization dis…
	…cards 'const' qualifier from pointer target type

	changed files:	sound/soc/codecs/wcd9xxx-mbhc.c
					sound/soc/codecs/wcd9xxx-mbhc.h

Signed-off-by: Akhil Narang <something@akhilnarang.xyz>